### ISSUE TITLE
Issue In GSTN API

### ISSUE THREAD

**Issue by aashishshar** [Risersoft/GSTN#1]
Hi,

Thanks for good post i am using this an i need your help. Kindly help me...
I am not able to RETSTATUS api call and its giving error message Unable to process and and also your getb2b and getgstr1summary methods not working kindly once check it again and when update this code..

Thanks,
Ashish Sharma

**Comment by absinghal** [comment]
Hello

Thanks for the feedback.

Please make sure you are using the latest updated version.

This being open source project, we encourage you to raise issues and also provide solutions so that those can be incorporated into the project. 

We will also keep updating the project based on our internal timelines.

Thanks
Abhishek Singhal

**Comment by aashishshar** [comment]
Yes I am using latest source code but their is no method for the RETSTATUS api.
GSTR Process is..
1)GetOTP--Working
2)GetAuthToken--working
3)Save GSTR1 invoice--Working
4)GET RETSTATUS of save GSTR1 data or  invoice--Not implemented
4)GetSummery--working but no data or no invoice section summary
5)FileGSTR1 using e-sign or DSC--Not working

Kindly please provide the solution for the i am very stuck on it.
and thanks for your g8 support.
Thanks,
Ashish Sharma

**Comment by absinghal** [comment]
OK - Let me see what can be done to speed up above points.

It will help if you can also email above to support at risersoft dot com using your official email address and contact details.

**Comment by gstezollution** [comment]
Hello Team,
Are you still working on it or not because nothing is working with v0.3 version of api. I am implementing a software using it. Kindly let me know, if you are working on it and how much time you will take for it..

Thanks,
Ashish Sharma
