### ISSUE TITLE
Where can i get .net core version of eSignASPLib.dll?

### ISSUE THREAD

**Issue by qloudau** [Risersoft/GSTN#2]
I am working on one .net core project and i have converted most of code from this repository in .net core version. I cant include **.dll** files directly to my .net core project. Please, let me know where can i get **.net core** version of **eSignASPLib.dll**?

**Comment by absinghal** [comment]
Good work. 
eSignASPLib.dll has been provided by the eSign Provider eMudhra. 

Two options:
- Check with eMudhra regarding .net core version
- Host a web service for eSign and consume it from your .Net core Project.

**Comment by gstezollution** [comment]
Hi,

Have you consumed GSTN api V0.3 or not..if not then you will do it or not??

**Comment by qloudau** [comment]
Hello Mr. Singhal,

While e-signing GSTR1 return in **GetUIDAIOtp** method of **Program** class  **eSignObj** is initialized using **eSignObj = new eSign(path);    //Get your own license file from e-Mudhra** statement. Can you please explain, **path** to what type of file and which file is system expecting here, please?

Regards,
Dhruv Pandya

**Comment by absinghal** [comment]
Mr Pandya / Mr Dwarapudi

If you sign up as ASP with eMudhra, they give you a license file, normally .LIC file.

This is what you pass as argument to the eSign constructor.

HTH

Best
